"""make certificate data flexible

Revision ID: 5e5d6e218b93
Revises: 1b46d682eee8
Create Date: 2026-10-08 19:01:28.039216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e5d6e218b93'
down_revision = '1b46d682eee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('course_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('completion_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('event_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('event_date', sa.Date(), nullable=True))

    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.drop_column('course_name')
        batch_op.drop_column('completion_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('course_name', mysql.VARCHAR(length=255), nullable=False))

    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_column('event_date')
        batch_op.drop_column('event_name')
        batch_op.drop_column('completion_date')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('course_name')
        batch_op.drop_column('organization')

    # ### end Alembic commands ###
